# update cache and upgrade all packages
- name: install wordpress
  hosts: myhosts
  remote_user: root

  vars_files:
    - vars/vars.yml

  tasks:
    - name: update apt cache and optionally upgrades system
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: install mysql server
      apt:
         name: mysql-server
         state: present

    - name: Add PPA for PHP 8.2
      apt_repository:
           repo: ppa:ondrej/php
           update_cache: true
           state: present

    - name: install php and common extensions
      apt:
        name: "{{ php_packages }}"
        state: present

